name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy Content
        run: mkdir -p ui/src/content && cp -r content/*.md ui/src/content/
      
      - name: Install Dependencies
        working-directory: ./ui
        run: npm ci
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          BASE_PATH: '/laundry-journal'
      
      - name: Create .nojekyll file
        run: touch ui/build/.nojekyll
      
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Create a temporary directory for the gh-pages branch
          mkdir -p /tmp/gh-pages
          cp -r ui/build/* /tmp/gh-pages/
          cp ui/build/.nojekyll /tmp/gh-pages/ || touch /tmp/gh-pages/.nojekyll
          
          # Create and push to gh-pages branch
          cd /tmp/gh-pages
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages
