name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy Content to UI
        run: mkdir -p ui/src/content && cp -r content/*.md ui/src/content/
      
      - name: Install Dependencies
        working-directory: ./ui
        run: npm ci
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          BASE_PATH: '/laundry-journal'
      
      - name: Create simple test page
        run: echo '<html><head><title>Test Page</title></head><body><h1>Test Page</h1></body></html>' > ui/build/test.html
      
      - name: Debug Contents
        run: ls -la ui/build/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/build
          force_orphan: true  # This creates a fresh branch with just our files
