name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy Content
        run: mkdir -p ui/src/content && cp -r content/*.md ui/src/content/
      
      - name: Install Dependencies
        working-directory: ./ui
        run: npm ci
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          BASE_PATH: '/laundry-journal'
      
      - name: Create .nojekyll file
        run: touch ui/build/.nojekyll
      
      - name: List build files
        run: ls -la ui/build/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/build
