name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy Content
        run: mkdir -p ui/src/content && cp -r content/*.md ui/src/content/
      
      - name: Install Dependencies
        working-directory: ./ui
        run: npm ci
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          BASE_PATH: '/laundry-journal'
      
      - name: Prepare for Deployment
        working-directory: ./ui
        run: |
          touch build/.nojekyll
          echo "Files in build directory:"
          ls -la build/
          
          # Ensure the redirect file exists and set proper permissions
          if [ ! -f "build/index.html" ]; then
            echo "Creating index.html"
            echo '<html><head><meta http-equiv="refresh" content="0;url=./laundry-journal/"></head><body>Redirecting...</body></html>' > build/index.html
            chmod 644 build/index.html
          fi
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui/build
          branch: svelte_frontend
          clean: false  # Changed to false to avoid removing files
