name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Copy Content
        run: mkdir -p ui/src/content && cp -r content/*.md ui/src/content/
      
      - name: Install Dependencies
        working-directory: ./ui
        run: npm ci
      
      - name: Build
        working-directory: ./ui
        run: npm run build
        env:
          BASE_PATH: '/laundry-journal'
      
      - name: Add .nojekyll
        working-directory: ./ui
        run: touch build/.nojekyll
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui/build
          branch: svelte_frontend
