name: Build and Deploy SvelteKit App
on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'ui/**'
      - 'src/**'
      - '.github/workflows/**'
      - 'README.md'
      - 'package.json'
      - 'svelte.config.js'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build SvelteKit app
        run: npm run build
        
      - name: Add .nojekyll file
        run: touch build/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # This should match your adapter-static output folder
          branch: svelte_frontend
          clean: true
